name: deploy-mfe-container

on:
  push:
    branches:
      - main
    paths:
      - "Package/Container/**"
defaults:
  run:
    working-directory: Package/Container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
